### ISSUE TITLE
image encoder 부분 질문입니다.

### ISSUE THREAD

**Issue by kyunghoyu** [HayeonLee/LDRFVD-CVPR16-pytorch#1]
안녕하세요? 
이 논문을 보며 따라서 구현해보고있는 중에 올려주신 코드를 참고하면서 하고있습니다.
다름아니라 논문에서는 image encoder로 googlenet을 사용하는데
올려주신 코드에서는  linear를 사용하셨는데 그 이유를 알고싶습니다.

감사합니다.

**Comment by HayeonLee** [comment]
안녕하세요. 이 코드는 제가 파이토치 연습 중에 구현해본 코드라서 최대한 심플하게 작성하려고 encoder를 linear layer를 사용하였습니다. image encoder로 torchvision에서 googlenet이나 resnet 등 다른 임베딩 네트워크를 사용하셔도 무방 할 것 같습니다.
